"""init_db

Revision ID: ef818af532f7
Revises: d89bd150dc0d
Create Date: 2026-02-14 10:37:13.248383

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ef818af532f7"
down_revision: Union[str, Sequence[str], None] = "d89bd150dc0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
